import React, { useState } from 'react';
import {
  X,
  FileText,
  FileDown,
  Upload,
  ChevronLeft,
  ChevronRight,
  ZoomIn,
  ZoomOut,
  Maximize2,
  Calendar,
  Layers,
  CheckCircle,
  Eye,
  ExternalLink,
  RotateCcw,
  Loader2
} from 'lucide-react';
import * as pdfjsLib from 'pdfjs-dist';
import { EPaperEdition, EPaperPage, MagazineConfig } from '../types';
import { THEME_CONFIGS } from '../utils/themeHelper';
import { PdfCanvasViewer } from './PdfCanvasViewer';

interface EPaperModalProps {
  isOpen: boolean;
  onClose: () => void;
  config: MagazineConfig;
  editions: EPaperEdition[];
  onUploadEdition: (edition: EPaperEdition) => void;
}

export const EPaperModal: React.FC<EPaperModalProps> = ({
  isOpen,
  onClose,
  config,
  editions,
  onUploadEdition,
}) => {
  const [selectedEditionIndex, setSelectedEditionIndex] = useState(0);
  const [activePageIndex, setActivePageIndex] = useState(0);
  const [zoomLevel, setZoomLevel] = useState(100);
  const [showUploadForm, setShowUploadForm] = useState(false);
  const [viewMode, setViewMode] = useState<'pdf_viewer' | 'broadsheet_summary'>('pdf_viewer');

  // New edition upload state
  const [newTitle, setNewTitle] = useState('The Hind Canadian Times — Special Midweek Edition');
  const [newVolume, setNewVolume] = useState('Vol. XXVI Issue 15');
  const [newDate, setNewDate] = useState('Wednesday, October 14, 2026');
  const [newPdfName, setNewPdfName] = useState('');
  const [newPdfUrl, setNewPdfUrl] = useState<string>('');
  const [newPdfFile, setNewPdfFile] = useState<File | null>(null);
  const [uploadSuccess, setUploadSuccess] = useState(false);
  const [isUploading, setIsUploading] = useState(false);

  if (!isOpen) return null;

  const theme = THEME_CONFIGS[config.theme] || THEME_CONFIGS.broadsheet;
  const currentEdition = editions[selectedEditionIndex] || editions[0];
  const currentPage = currentEdition?.pages?.[activePageIndex] || currentEdition?.pages?.[0];

  const handleNextPage = () => {
    if (currentEdition?.pages && activePageIndex < currentEdition.pages.length - 1) {
      setActivePageIndex(activePageIndex + 1);
    }
  };

  const handlePrevPage = () => {
    if (activePageIndex > 0) {
      setActivePageIndex(activePageIndex - 1);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      setNewPdfName(file.name);
      setNewPdfFile(file);

      // Read as Data URL (base64) so it can be stored persistently in IndexedDB & rendered via Canvas
      const reader = new FileReader();
      reader.onload = (event) => {
        const dataUrl = event.target?.result as string;
        if (dataUrl) {
          setNewPdfUrl(dataUrl);
        }
      };
      reader.readAsDataURL(file);

      // Auto-populate Title if user hasn't edited
      if (!newTitle || newTitle.includes('Special Midweek Edition')) {
        const cleanName = file.name.replace(/\.[^/.]+$/, '').replace(/[_-]/g, ' ');
        setNewTitle(`The Hind Canadian Times — ${cleanName}`);
      }
    }
  };

  const handleUploadSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsUploading(true);

    try {
      let finalPdfDataUrl = newPdfUrl;
      let totalPagesDetected = 4;
      let previewCover = '/src/assets/images/newspaper_masthead_hero_1791385485215.jpg';

      if (newPdfFile) {
        // Read file arrayBuffer
        const arrayBuffer = await newPdfFile.arrayBuffer();

        // If data url not yet generated by reader, generate it now
        if (!finalPdfDataUrl) {
          finalPdfDataUrl = await new Promise<string>((resolve, reject) => {
            const reader = new FileReader();
            reader.onload = () => resolve(reader.result as string);
            reader.onerror = reject;
            reader.readAsDataURL(newPdfFile);
          });
        }

        // Use PDF.js to inspect actual page count and render real cover thumbnail from page 1
        try {
          const doc = await pdfjsLib.getDocument({ data: arrayBuffer }).promise;
          totalPagesDetected = doc.numPages || 1;
          const page1 = await doc.getPage(1);
          const viewport = page1.getViewport({ scale: 0.45 });
          const canvas = document.createElement('canvas');
          canvas.width = viewport.width;
          canvas.height = viewport.height;
          const ctx = canvas.getContext('2d');
          if (ctx) {
            await page1.render({ canvasContext: ctx, viewport }).promise;
            previewCover = canvas.toDataURL('image/jpeg', 0.85);
          }
        } catch (inspectErr) {
          console.warn('PDF inspection notice:', inspectErr);
        }
      }

      if (!finalPdfDataUrl) {
        finalPdfDataUrl = currentEdition.pdfDataUrl || currentEdition.pdfUrl || '';
      }

      const formattedSize = newPdfFile
        ? `${(newPdfFile.size / (1024 * 1024)).toFixed(1)} MB (Uploaded PDF)`
        : '14.2 MB (Print PDF)';

      // Dynamically build page outlines matching the detected pages
      const generatedPages: EPaperPage[] = [];
      for (let p = 1; p <= Math.min(totalPagesDetected, 16); p++) {
        generatedPages.push({
          pageNumber: p,
          title: `Page ${p} — ${p === 1 ? 'Front Page Broadsheet' : `Broadsheet Page ${p} Dispatch`}`,
          headline: p === 1 ? newTitle.toUpperCase() : `BROADSHEET PAGE ${p} ARCHIVE & EDITORIAL`,
          summary: p === 1
            ? `Official broadsheet print edition published on ${newDate}. Front-page exclusives, bilateral reporting and community news.`
            : `Comprehensive page ${p} coverage, provincial reports, business columns and diaspora notices.`,
          previewImageUrl: previewCover,
        });
      }

      const createdEdition: EPaperEdition = {
        id: `epaper-${Date.now()}`,
        title: newTitle,
        volumeIssue: newVolume,
        date: newDate,
        coverImageUrl: previewCover,
        pdfUrl: finalPdfDataUrl,
        pdfDataUrl: finalPdfDataUrl,
        pdfFileName: newPdfName || 'edition.pdf',
        isUserUploaded: true,
        totalPages: totalPagesDetected,
        fileSize: formattedSize,
        downloadsCount: 1,
        pages: generatedPages,
      };

      onUploadEdition(createdEdition);
      setUploadSuccess(true);
      setTimeout(() => {
        setUploadSuccess(false);
        setShowUploadForm(false);
        setIsUploading(false);
        setSelectedEditionIndex(0);
        setActivePageIndex(0);
        setViewMode('pdf_viewer'); // Switch directly to the newly uploaded PDF
      }, 700);
    } catch (err) {
      console.warn('Upload error:', err);
      setIsUploading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/85 backdrop-blur-xs overflow-y-auto">
      <div className={`w-full max-w-5xl max-h-[94vh] rounded-2xl border ${theme.border} ${theme.surfaceBg} ${theme.textPrimary} shadow-2xl flex flex-col overflow-hidden my-auto`}>
        {/* Top Control Bar */}
        <div className={`p-4 border-b ${theme.border} ${theme.canvasBg} flex flex-wrap items-center justify-between gap-3`}>
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-red-100 text-red-700">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-serif font-black text-base sm:text-lg">
                  Digital E-Paper Portal (PDF Editions)
                </h3>
                <span className="text-[10px] font-mono bg-red-800 text-white px-2 py-0.5 rounded-full">
                  Print Replica
                </span>
              </div>
              <div className="text-xs text-neutral-500 font-mono">
                {currentEdition.volumeIssue} &middot; {currentEdition.date}
              </div>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {/* Upload New PDF E-Paper trigger */}
            <button
              onClick={() => setShowUploadForm(!showUploadForm)}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold border flex items-center gap-1.5 transition-colors ${
                showUploadForm
                  ? 'bg-neutral-800 text-white'
                  : 'bg-emerald-700 hover:bg-emerald-800 text-white'
              }`}
            >
              <Upload className="w-3.5 h-3.5" />
              <span>{showUploadForm ? 'Back to Reader' : 'Upload New E-Paper (PDF)'}</span>
            </button>

            {/* Download PDF edition */}
            <button
              onClick={() => {
                try {
                  const source = currentEdition.pdfDataUrl || currentEdition.pdfUrl;
                  if (!source) return;
                  const a = document.createElement('a');
                  a.href = source;
                  a.download = currentEdition.pdfFileName || `${currentEdition.title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
                  document.body.appendChild(a);
                  a.click();
                  a.remove();
                } catch (err) {
                  console.warn('Download error:', err);
                }
              }}
              className="px-3 py-1.5 rounded-lg bg-red-700 hover:bg-red-800 text-white text-xs font-semibold flex items-center gap-1.5 transition-colors shadow-xs"
              title="Download full PDF print edition"
            >
              <FileDown className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Download PDF ({currentEdition.fileSize})</span>
              <span className="sm:hidden">Download</span>
            </button>

            <button
              onClick={onClose}
              className="p-1.5 rounded-lg hover:bg-neutral-200 text-neutral-700"
              aria-label="Close E-Paper"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content Area */}
        {showUploadForm ? (
          /* PDF Upload Studio */
          <div className="flex-1 overflow-y-auto p-6 sm:p-10 space-y-6">
            <div className="max-w-2xl mx-auto space-y-6">
              <div>
                <h4 className="text-xl font-bold font-serif">
                  Upload & Publish New PDF E-Paper Edition
                </h4>
                <p className="text-xs text-neutral-500 mt-1">
                  Upload complete weekly or monthly broadsheet newspaper editions in PDF format. Registered with Canada National Library archive.
                </p>
              </div>

              {uploadSuccess ? (
                <div className="py-12 text-center space-y-3">
                  <CheckCircle className="w-12 h-12 text-emerald-600 mx-auto animate-bounce" />
                  <h4 className="text-lg font-bold text-emerald-800">
                    E-Paper Edition Uploaded & Archived!
                  </h4>
                  <p className="text-xs text-neutral-500">Available immediately in the reader and download center.</p>
                </div>
              ) : (
                <form onSubmit={handleUploadSubmit} className="space-y-4 text-xs">
                  <div>
                    <label className="font-semibold block mb-1">Edition Title</label>
                    <input
                      type="text"
                      required
                      value={newTitle}
                      onChange={(e) => setNewTitle(e.target.value)}
                      className="w-full p-2.5 rounded-lg border border-neutral-300 font-serif"
                    />
                  </div>

                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                    <div>
                      <label className="font-semibold block mb-1">Volume &amp; Issue Number</label>
                      <input
                        type="text"
                        required
                        value={newVolume}
                        onChange={(e) => setNewVolume(e.target.value)}
                        className="w-full p-2 rounded-lg border border-neutral-300 font-mono"
                      />
                    </div>
                    <div>
                      <label className="font-semibold block mb-1">Publication Date</label>
                      <input
                        type="text"
                        required
                        value={newDate}
                        onChange={(e) => setNewDate(e.target.value)}
                        className="w-full p-2 rounded-lg border border-neutral-300"
                      />
                    </div>
                  </div>

                  {/* Drag-and-drop or select PDF */}
                  <div className="p-6 border-2 border-dashed border-red-300 rounded-xl bg-red-50/40 text-center space-y-2">
                    <FileText className="w-8 h-8 text-red-600 mx-auto" />
                    <div className="font-semibold text-neutral-800">
                      Upload Broadsheet Print Replica (PDF File)
                    </div>
                    <p className="text-[11px] text-neutral-500">
                      Standard broadsheet format (up to 50 MB, multi-page vector or scanned PDF)
                    </p>
                    <input
                      type="file"
                      accept=".pdf,application/pdf"
                      onChange={handleFileChange}
                      className="text-xs file:mr-2 file:py-1 file:px-3 file:rounded-md file:border-0 file:text-xs file:font-semibold file:bg-red-800 file:text-white cursor-pointer"
                    />
                    {newPdfName && (
                      <div className="p-2 rounded bg-emerald-100 border border-emerald-300 text-emerald-800 font-mono font-bold text-xs pt-2">
                        ✓ Selected File: {newPdfName} (Ready to View &amp; Publish)
                      </div>
                    )}
                  </div>

                  <div className="pt-3 border-t border-neutral-300 flex justify-end gap-3">
                    <button
                      type="button"
                      onClick={() => setShowUploadForm(false)}
                      className="px-4 py-2 rounded-lg border border-neutral-300 hover:bg-neutral-100"
                    >
                      Cancel
                    </button>
                    <button
                      type="submit"
                      disabled={isUploading}
                      className="px-6 py-2 rounded-lg bg-emerald-700 hover:bg-emerald-800 disabled:opacity-50 text-white font-bold flex items-center gap-2"
                    >
                      {isUploading && <Loader2 className="w-4 h-4 animate-spin" />}
                      <span>{isUploading ? 'Processing & Archiving...' : 'Publish E-Paper Edition'}</span>
                    </button>
                  </div>
                </form>
              )}
            </div>
          </div>
        ) : (
          /* Multi-Page E-Paper Reader */
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Viewer Toolbar */}
            <div className={`px-4 py-2 border-b ${theme.border} flex flex-wrap items-center justify-between gap-2 text-xs bg-neutral-100`}>
              <div className="flex items-center gap-2">
                {/* View Mode Toggle */}
                <div className="flex items-center bg-white rounded-lg p-0.5 border border-neutral-300">
                  <button
                    onClick={() => setViewMode('pdf_viewer')}
                    className={`px-2.5 py-1 rounded-md text-xs font-semibold flex items-center gap-1 transition-colors ${
                      viewMode === 'pdf_viewer'
                        ? 'bg-red-800 text-white shadow-xs'
                        : 'text-neutral-700 hover:text-black'
                    }`}
                  >
                    <FileText className="w-3.5 h-3.5" />
                    <span>PDF Document View</span>
                  </button>
                  <button
                    onClick={() => setViewMode('broadsheet_summary')}
                    className={`px-2.5 py-1 rounded-md text-xs font-semibold flex items-center gap-1 transition-colors ${
                      viewMode === 'broadsheet_summary'
                        ? 'bg-red-800 text-white shadow-xs'
                        : 'text-neutral-700 hover:text-black'
                    }`}
                  >
                    <Eye className="w-3.5 h-3.5" />
                    <span>Broadsheet Layout</span>
                  </button>
                </div>

                {/* Page Navigator (For Broadsheet Mode) */}
                {viewMode === 'broadsheet_summary' && (
                  <div className="flex items-center gap-1 ml-2">
                    <button
                      onClick={handlePrevPage}
                      disabled={activePageIndex === 0}
                      className="p-1 rounded border border-neutral-300 disabled:opacity-30 hover:bg-white"
                      title="Previous Page"
                    >
                      <ChevronLeft className="w-4 h-4" />
                    </button>

                    <div className="flex items-center gap-1 font-mono font-semibold">
                      <span>Page</span>
                      <select
                        value={activePageIndex}
                        onChange={(e) => setActivePageIndex(parseInt(e.target.value))}
                        className="p-1 rounded border border-neutral-300 bg-white"
                      >
                        {currentEdition.pages.map((p, idx) => (
                          <option key={idx} value={idx}>
                            {p.pageNumber} of {currentEdition.pages.length} ({p.title.split('—')[1] || p.title})
                          </option>
                        ))}
                      </select>
                    </div>

                    <button
                      onClick={handleNextPage}
                      disabled={activePageIndex === currentEdition.pages.length - 1}
                      className="p-1 rounded border border-neutral-300 disabled:opacity-30 hover:bg-white"
                      title="Next Page"
                    >
                      <ChevronRight className="w-4 h-4" />
                    </button>
                  </div>
                )}
              </div>

              {/* Archive Edition Switcher */}
              <div className="flex items-center gap-2">
                <span className="text-neutral-500 font-mono text-[11px]">Edition:</span>
                <select
                  value={selectedEditionIndex}
                  onChange={(e) => {
                    setSelectedEditionIndex(parseInt(e.target.value));
                    setActivePageIndex(0);
                  }}
                  className="p-1.5 rounded border border-neutral-300 bg-white text-xs font-medium max-w-56 truncate"
                >
                  {editions.map((ed, idx) => (
                    <option key={ed.id} value={idx}>
                      {ed.title} ({ed.date})
                    </option>
                  ))}
                </select>
              </div>

              {/* Zoom Controls (For Broadsheet Mode) */}
              {viewMode === 'broadsheet_summary' && (
                <div className="flex items-center gap-1">
                  <button
                    onClick={() => setZoomLevel(Math.max(75, zoomLevel - 15))}
                    className="p-1 rounded border border-neutral-300 hover:bg-white"
                    title="Zoom Out"
                  >
                    <ZoomOut className="w-3.5 h-3.5" />
                  </button>
                  <span className="font-mono text-[11px] tabular-nums px-1">{zoomLevel}%</span>
                  <button
                    onClick={() => setZoomLevel(Math.min(150, zoomLevel + 15))}
                    className="p-1 rounded border border-neutral-300 hover:bg-white"
                    title="Zoom In"
                  >
                    <ZoomIn className="w-3.5 h-3.5" />
                  </button>
                </div>
              )}
            </div>

            {/* Display Body: High-Fidelity Canvas PDF Viewer vs Broadsheet */}
            {viewMode === 'pdf_viewer' ? (
              <div className="flex-1 w-full min-h-[500px] bg-neutral-950 flex flex-col overflow-hidden">
                <PdfCanvasViewer
                  key={currentEdition.id}
                  pdfSource={currentEdition.pdfDataUrl || currentEdition.pdfUrl}
                  fileName={currentEdition.pdfFileName || `${currentEdition.title}.pdf`}
                  title={currentEdition.title}
                  onTotalPagesDetected={(detectedPages, previewUrl) => {
                    if (previewUrl && (!currentEdition.coverImageUrl || !currentEdition.coverImageUrl.startsWith('data:'))) {
                      currentEdition.coverImageUrl = previewUrl;
                    }
                  }}
                  onFallbackToBroadsheet={() => setViewMode('broadsheet_summary')}
                />
              </div>
            ) : (
              /* Broadsheet Page Canvas */
              <div className="flex-1 overflow-auto p-4 sm:p-8 bg-neutral-900/90 flex justify-center">
                <div
                  style={{ transform: `scale(${zoomLevel / 100})`, transformOrigin: 'top center' }}
                  className="w-full max-w-2xl bg-[#fdfcf7] text-[#1c1917] p-8 rounded-lg shadow-2xl border-4 border-neutral-400 space-y-6 transition-transform"
                >
                  {/* Print Page Header */}
                  <div className="border-b-2 border-black pb-2 flex items-center justify-between text-xs font-serif uppercase tracking-widest">
                    <span className="font-bold">THE HIND CANADIAN TIMES</span>
                    <span className="font-mono font-semibold">{currentPage.title}</span>
                    <span className="font-mono">{currentEdition.date}</span>
                  </div>

                  {/* Broadsheet Headline & Columns */}
                  <div className="space-y-4">
                    <h2 className="text-2xl sm:text-3xl font-black font-serif uppercase tracking-tight leading-tight border-b border-neutral-300 pb-2">
                      {currentPage.headline}
                    </h2>

                    {/* Page visual */}
                    {currentPage.previewImageUrl && (
                      <div className="rounded border border-neutral-400 overflow-hidden aspect-16/9 bg-neutral-200">
                        <img
                          src={currentPage.previewImageUrl}
                          alt={currentPage.headline}
                          className="w-full h-full object-cover"
                        />
                      </div>
                    )}

                    {/* Multi-column newsprint simulation */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 text-xs font-serif leading-relaxed text-justify">
                      <p>
                        <strong>{currentEdition.date.split(',')[1] || 'OTTAWA'}</strong> &mdash; {currentPage.summary} The Hind Canadian Times print edition provides in-depth forensic investigation into immigration policies, parliamentary debates, and grassroots diaspora achievements across Canada and India.
                      </p>
                      <p>
                        Subscribers can access full vector archives dating back to 2024. Commercial and community advertisers are featured across prominent full-page, half-page, and classified columns in high-resolution print press runs.
                      </p>
                    </div>
                  </div>

                  {/* Print Page Footer */}
                  <div className="border-t border-black pt-2 flex items-center justify-between text-[10px] font-mono text-neutral-500">
                    <span>Page {currentPage.pageNumber} of {currentEdition.totalPages}</span>
                    <span>Registered ISSN 1712-4980 &middot; Printed in Canada</span>
                    <span>thehindcanadiantimes.com</span>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
};
